spring.application.name=hr-payroll
server.port=8101

spring.cloud.discovery.client.simple.enabled=true

spring.cloud.discovery.client.simple.instances.hr-workers[0].uri=http://localhost:8001
spring.cloud.discovery.client.simple.instances.hr-workers[1].uri=http://localhost:8002
